export const CODE_RESPONSE = {
  POST_SUCCESS: 201,
  GET_SUCCESS: 200,
  POST_FAILUE: 202, // tạo, update nhưng có lỗi (k thông báo)
  POST_GET_FAILUE: 400,
  SEVER_ERROR: 500,
  AUTHENTICATION_FAILED: 403,
  NOT_AUTHORIZED: 401,
  MAINTAIN_SYSTEM: 407,
  NOT_FOUND: 404,
};
